<?php
return [
    'parts' => [
        'Body Luar Atas',
        // 'Body Luar Bawah',
        // 'Body Luar Kanan',
        // 'Body Luar Kiri',
        // 'Body Luar Belakang',
        // 'Body Luar Pintu',
        // 'Kanal U Tulangan',
        // 'Tulangan Hudimifier',
        // 'Body Dalam Pintu',
        // 'Body Dalam Belakang',
        // 'Body Luar Display',
        // 'Body Luar Sambungan Atas',
        // 'Tulang Kaki Roda',
        // 'Tulang Body Dalam',
        // 'Body Dalam Kanan',
        // 'Body Dalam  Kiri',

        // 'Body Dalam Atas',
        // 'Body Dalam Bawah',
        // 'Kap Blower',
        // 'Talang Air Bawah',
        // 'Sekat Dinding Belakang',
        // 'Sekat Dinding Belakang 2',
        // 'Tiang Lampu Dalam',
        // 'Tiang Lampu Luar',
        // 'Dinding Display Belakang Tengah',
        // 'Dinding Display Belakang Kanan',
        // 'Dinding Display Belakang Kiri',
        // 'Body Luar Evaporator Reservoir',
        // 'Body Dalam Evaporator Reservoir',
        // 'Tutup Atas Chamber Kanan',
        // 'Tutup Atas Chamber Kiri',
        // 'Tutup Atas Chamber Tengah',

        // 'Body Luar Cooling',
        // 'Nampan Cooling',
        // 'Tampungan Humidifier',
        // 'Tampungan Humidifier Kanan',
        // 'Tampungan Humidifier Kiri',
        // 'Box Level Switch',
        // 'Box Level Switch Kanan',
        // 'Box Level Switch Kiri',
        // 'Tutup Box Level Switch',
        // 'Water Container',
        // 'Water Container Kanan & Kiri',
        // 'Tutup Water Container',
        // 'Bracket for Container',
    ],
];
